"""Type stubs for streamlink library."""

from typing import Any, Dict

def streams(url: str, **options: Any) -> Dict[str, Any]: ...

class StreamlinkError(Exception): ...
class NoPluginError(StreamlinkError): ...
class PluginError(StreamlinkError): ...
